### ISSUE TITLE
Kubelet Startup Crashes systemd on Garden Linux

### ISSUE THREAD

**Issue by marwinski** [gardener/gardener-extension-os-gardenlinux#4]
**What happened**:

systemd crashes when the node starts. While this is most likely a systemd issue (that unfortunately we are not able to fix in a short period of time) we need a workaround. It also appears problematic to run docker containers in that restricted context and at that time where docker might not be fully started.

This happens with Garden Linux and only on GCP (AWS is fine). It happens with various systemd versions (244, 245).

**What you expected to happen**:

systemd does not crash

**How to reproduce it (as minimally and precisely as possible)**:

Create a gardenlinux cluster on GCP (but there is no need to).

**Anything else we need to know?**:

Garden Linux ticket (still private): https://github.com/MalteJ/gardenlinux-manifest/issues/17

In the kubelet.service file replace the docker run command with the two following lines (this has been tested). 

```
#ExecStartPre=/usr/bin/docker run --rm -v /opt/bin:/opt/bin:rw eu.gcr.io/sap-se-gcr-k8s-public/modified3/k8s_gcr_io/hyperkube:v1.15.11 /bin/sh -c "cp /usr/local/bin/kubelet /opt/bin"
ExecStartPre=wget -O /opt/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/v1.15.11/bin/linux/amd64/kubelet
ExecStartPre=chmod 755 /opt/bin/kubelet
```

Alternatively the following should also work (but not tested):

ExecStartPre=sh -c 'docker cp $(docker create <image>):/hyperkube /opt/bin/kubelet'

**Environment**:

- Gardener version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by rfranzke** [comment]
> ExecStartPre=wget -O /opt/bin/kubelet https://storage.googleapis.com/kubernetes-release/release/v1.15.11/bin/linux/amd64/kubelet

We always avoided to download stuff from the internet. With the current approach we are starting a container and are copying out the necessary binaries. The rationale behind it is that we anyways have access to a container registry, hence, we can make assumptions about it. Downloading from the internet does not work well in fenced environments.
/cc @jia-jerry @vlerenc

**Comment by vpnachev** [comment]
Even if we "fix" the `kubelet` image, this issue will be still affecting every other docker image that must be pulled on the node. 

@marwinski could you check what has been changed on the image since `garden-linux-dev-gcp-12` which was working perfectly fine ?

**Comment by marwinski** [comment]
I will be checking alternatives. I don't know why Garden Linux 12 worked fine - we did not really change anything but there is the possibility that an updated component sneaked in from a new Debian snapshot.

Anyway, we are sure this is a timing issue. When we run the kubelet start (or restart) at a later point in time we don't see that issue. Also, adding a "sleep 5" to the pre-conditions avoids this problem (this said , I would not consider this a safe workaround).

**Comment by marwinski** [comment]
It appears that the problem was introduced by a new apparmor version.

Version in release 12: apparmor 2.13.3-7 
Version in release 18: apparmor 2.13.4-1

When downgrading to 2.13.3-7 we do not see the systemd crash. This is the changelog 

https://tracker.debian.org/news/1114024/accepted-apparmor-2134-1-source-into-unstable/

(which unfortunately does not ring any bells). We will build a new image for testing.

**Comment by vpnachev** [comment]
The issue has been fixed upstream in Garden Linux and is no longer observed.
/close
