### ISSUE TITLE
Use systemd cgroup driver on cgroupsv2 

### ISSUE THREAD

**Issue by danielfoehrKn** [gardener/gardener-extension-os-gardenlinux#78]
**How to categorize this issue?**

/area os
/kind enhancement
/os garden-linux

**What would you like to be added**:

Gardenlinux nodes should be configured with the systemd cgroup driver for GL using cgroupsv2. 

**Why is this needed**:

- Recommended by [Kubernetes documentation](https://kubernetes.io/docs/concepts/architecture/cgroups/#requirements) (but does not state a reason why, and AFAIK there are no inherent problems with using the cgroupfs driver on cgroupsv2)
- We have seen problems with nested docker-in-docker type setups (also for containerd). If the container runtime uses cgroupfs (default for OS without running systemd e.g in a `dind`-pod), then the container runtime decides to place the started containers not under the parent pod's cgroup, but under a separate sibling cgroup. This circumvents any cgroup settings on the parent pod's cgroup (e.g memory limits) to apply to the containers started by the nested container runtime. 
   - Using systemd as cgroup driver, the container runtimes behave correctly (reason unknown, implementation detail in dockerd and containerd). 

For the implementation, make sure:

- Ensure the systemd cgroup driver is set for both the kubelet and the container runtime. Be aware the Gardener generates the kubelet configuration in the Gardenlet (not in the OS extension). Hence, need to either change the kubelet config centrally to use the systemd driver, or provide a GL specific mechanism e.g via systemd service to adjust the kubelet config on the host.  
- Make sure that GL `576.XX `that has a hybrid cgroup setup works with systemd as the cgroup driver. If this works: GL `576.XX`  is already > 1 year old, the extension can just enforce the systemd derived for all nodes.
- Ensure node pools are rolled upon switch of the cgroup driver.

**Comment by voelzmo** [comment]
Not saying this was done the most "correct" way, but this configuration exists in the coreos extension already – including re-configuring kubelet on the fly: https://github.com/gardener/gardener-extension-os-coreos/pull/40

**Comment by vpnachev** [comment]
The umbrella issue about the switch from cgroupfs to systemd cgroup driver is here https://github.com/gardener/gardener/issues/5325
